#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)

# this values must exists in the json stdin
agent.set_env("WEBPASSWORD", data["webpassword"])
agent.set_env("DNS1", data["dns1"])
agent.set_env("DNS2", data["dns2"])
