#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)

# this values must exists in the json stdin
password = {"WEBPASSWORD":data["webpassword"]}
agent.write_envfile("password.env", password)
